import path from "path";
import { readJson } from "../../utils/fs";
import { currentDateISO } from "../../utils/date";
import { agentResultBundleSchema, type AgentResultBundle } from "../../schemas/agentResultBundle";
import { agentTaskContractSchema, type AgentTaskContract } from "../../schemas/agentTaskContract";
import { runReconcile } from "../reconciliation/runReconcile";
import { readAgentRunRecord, writeReconciliationStatus, type AgentRunRecord } from "./runRecord";
import { AGENT_RUNTIME_OUTPUT_SCHEMA_VERSION, type AgentRuntimeCommandResultBase } from "./output";
import { toPosixRelativePath } from "./paths";
import { assertRealpathWithinRoot } from "../../utils/symlinkPolicy";
import { appendAgentAuditEvent } from "./audit";
import { agentEscalationDraftSchema } from "../../schemas/agentEscalationDraft";

export class ReconcileError extends Error {
  constructor(
    public readonly code: string,
    message: string,
  ) {
    super(message);
    this.name = "ReconcileError";
  }
}

export interface ReconcileAgentRunOptions {
  runId: string;
  cwd?: string;
  apply?: boolean;
  createDiscovered?: boolean;
}

export interface ReconcileAgentRunResult extends AgentRuntimeCommandResultBase {
  status: "reconciled";
  reconciliationStatus: "completed";
  reportPath: string;
  reportMarkdownPath: string;
  runRecordPath: string;
  apply: boolean;
  createDiscovered: boolean;
  discoveredDraftPath?: string;
  escalationDraftPaths: string[];
}

function resolveRepoPath(cwd: string, value: string): string {
  return path.resolve(cwd, value);
}

function assertRunIsReconcileEligible(record: AgentRunRecord): void {
  if (record.status !== "validation-passed" || !record.ok) {
    throw new ReconcileError(
      "PAA010",
      `Run ${record.runId} has not passed validation and cannot be reconciled.`,
    );
  }
}

async function loadReconcileArtifacts(
  record: AgentRunRecord,
  cwd: string,
): Promise<{ result: AgentResultBundle; contract: AgentTaskContract | null }> {
  const resultPath = resolveRepoPath(cwd, record.resultPath);

  let rawResult: unknown;
  try {
    rawResult = await readJson<unknown>(resultPath);
  } catch {
    throw new ReconcileError(
      "PAA002",
      `Imported result artifact is missing for run ${record.runId}: ${record.resultPath}`,
    );
  }

  const result = agentResultBundleSchema.parse(rawResult);

  if (!record.contractPath) {
    return { result, contract: null };
  }

  const contractPath = resolveRepoPath(cwd, record.contractPath);
  let rawContract: unknown;
  try {
    rawContract = await readJson<unknown>(contractPath);
  } catch {
    throw new ReconcileError(
      "PAA002",
      `Prepared contract artifact is missing for run ${record.runId}: ${record.contractPath}`,
    );
  }

  return {
    result,
    contract: agentTaskContractSchema.parse(rawContract),
  };
}

async function maybeWriteDiscoveredDraft(input: {
  cwd: string;
  runId: string;
  taskId: string;
  createDiscovered: boolean;
  proposedActions: string[];
}): Promise<string | undefined> {
  if (!input.createDiscovered) {
    return undefined;
  }

  const fileName = `discovered-${input.taskId}-${input.runId}-${currentDateISO()}.md`;
  const targetPath = path.join(input.cwd, ".project-arch", "reconcile", fileName);

  const lines = [
    `# Discovered Draft for Run ${input.runId}`,
    "",
    `- taskId: ${input.taskId}`,
    `- runId: ${input.runId}`,
    "",
    "## Proposed Follow-up Work",
    "",
    ...(input.proposedActions.length > 0
      ? input.proposedActions.map((action) => `- [ ] ${action}`)
      : ["- [ ] No proposed actions were generated by reconciliation."]),
    "",
  ];

  const fs = await import("fs-extra");
  await fs.default.ensureDir(path.dirname(targetPath));
  await fs.default.writeFile(targetPath, lines.join("\n"), "utf8");

  return toPosixRelativePath(input.cwd, targetPath);
}

async function writeEscalationDrafts(input: {
  cwd: string;
  runId: string;
  taskId: string;
  decisionRequests: AgentResultBundle["decisionRequests"];
}): Promise<string[]> {
  const requests = input.decisionRequests ?? [];
  if (requests.length === 0) {
    return [];
  }

  const fs = await import("fs-extra");
  const draftsDir = path.join(input.cwd, ".project-arch", "reconcile", "escalations");
  await fs.default.ensureDir(draftsDir);

  const paths: string[] = [];
  for (const [index, request] of requests.entries()) {
    const sequence = String(index + 1).padStart(2, "0");
    const baseName = `${input.taskId}-${input.runId}-${sequence}-${request.escalationType}`;
    const jsonPath = path.join(draftsDir, `${baseName}.json`);
    const markdownPath = path.join(draftsDir, `${baseName}.md`);

    const draft = agentEscalationDraftSchema.parse({
      schemaVersion: "2.0",
      type: "agent-escalation-draft",
      status: "draft",
      runId: input.runId,
      taskId: input.taskId,
      escalationType: request.escalationType,
      severity: request.severity,
      summary: request.summary,
      details: request.details,
      options: request.options,
      recommendedNextStep: request.recommendedNextStep,
      sourceCreatedAt: request.createdAt,
      promotedAt: new Date().toISOString(),
    });

    await fs.default.writeJson(jsonPath, draft, { spaces: 2 });

    const markdownLines = [
      `# Escalation Draft: ${request.escalationType}`,
      "",
      `- runId: ${input.runId}`,
      `- taskId: ${input.taskId}`,
      `- severity: ${request.severity}`,
      `- recommendedNextStep: ${request.recommendedNextStep}`,
      "",
      "## Summary",
      "",
      request.summary,
      "",
      "## Details",
      "",
      ...request.details.map((detail) => `- ${detail}`),
      "",
      "## Options",
      "",
      ...request.options.map((option) => `- ${option.label}: ${option.impact}`),
      "",
      "## Promotion Boundary",
      "",
      "This draft is reviewable repository output and does not represent accepted canonical decision/task state.",
      "",
    ];

    await fs.default.writeFile(markdownPath, markdownLines.join("\n"), "utf8");

    paths.push(toPosixRelativePath(input.cwd, jsonPath));
    paths.push(toPosixRelativePath(input.cwd, markdownPath));
  }

  return paths;
}

async function applyReconcileLatestPointer(input: {
  cwd: string;
  taskId: string;
  runId: string;
  reportId: string;
  reportStatus: string;
  reportDate: string;
  reportPath: string;
  reportMarkdownPath: string;
}): Promise<void> {
  const fs = await import("fs-extra");
  const latestDir = path.join(input.cwd, ".project-arch", "reconcile", "latest");
  const pointerPath = path.join(latestDir, `${input.taskId}.json`);

  await fs.default.ensureDir(latestDir);
  await assertRealpathWithinRoot(pointerPath, input.cwd, "reconciliation latest pointer");

  await fs.default.writeJson(
    pointerPath,
    {
      schemaVersion: "2.0",
      taskId: input.taskId,
      generatedAt: currentDateISO(),
      latest: {
        id: input.reportId,
        runId: input.runId,
        date: input.reportDate,
        status: input.reportStatus,
        jsonPath: input.reportPath,
        markdownPath: input.reportMarkdownPath,
      },
    },
    { spaces: 2 },
  );
}

export async function reconcileAgentRun(
  options: ReconcileAgentRunOptions,
): Promise<ReconcileAgentRunResult> {
  const cwd = options.cwd ?? process.cwd();
  const apply = options.apply === true;
  const createDiscovered = options.createDiscovered === true;

  let runRecord: AgentRunRecord;
  try {
    runRecord = await readAgentRunRecord(options.runId, cwd);
  } catch {
    throw new ReconcileError(
      "PAA002",
      `Validated run record not found for run ${options.runId}. Expected .project-arch/agent-runtime/runs/${options.runId}.json.`,
    );
  }

  assertRunIsReconcileEligible(runRecord);

  try {
    const { result } = await loadReconcileArtifacts(runRecord, cwd);

    const reconcileOutput = await runReconcile({
      taskId: runRecord.taskId,
      runId: runRecord.runId,
      additionalChangedFiles: result.changedFiles,
      cwd,
    });

    const discoveredDraftPath = await maybeWriteDiscoveredDraft({
      cwd,
      runId: runRecord.runId,
      taskId: runRecord.taskId,
      createDiscovered,
      proposedActions: reconcileOutput.report.proposedActions,
    });
    const escalationDraftPaths = await writeEscalationDrafts({
      cwd,
      runId: runRecord.runId,
      taskId: runRecord.taskId,
      decisionRequests: result.decisionRequests,
    });

    const reportPath = toPosixRelativePath(cwd, reconcileOutput.jsonPath);
    const reportMarkdownPath = toPosixRelativePath(cwd, reconcileOutput.markdownPath);

    if (apply) {
      await applyReconcileLatestPointer({
        cwd,
        taskId: runRecord.taskId,
        runId: runRecord.runId,
        reportId: reconcileOutput.report.id,
        reportStatus: reconcileOutput.report.status,
        reportDate: reconcileOutput.report.date,
        reportPath,
        reportMarkdownPath,
      });
    }

    await writeReconciliationStatus(
      {
        runId: runRecord.runId,
        reconciliationStatus: "completed",
        reconciliationReportPath: reportPath,
        escalationDraftPaths,
        reconciledAt: new Date().toISOString(),
      },
      cwd,
    );

    await appendAgentAuditEvent(
      {
        command: "reconcile",
        status: "success",
        runId: runRecord.runId,
        taskId: runRecord.taskId,
        metadata: {
          reportPath,
          discoveredDraftPath,
          escalationDraftCount: escalationDraftPaths.length,
          apply,
          createDiscovered,
        },
      },
      cwd,
    );

    return {
      schemaVersion: AGENT_RUNTIME_OUTPUT_SCHEMA_VERSION,
      runId: runRecord.runId,
      taskId: runRecord.taskId,
      status: "reconciled",
      reconciliationStatus: "completed",
      reportPath,
      reportMarkdownPath,
      runRecordPath: `.project-arch/agent-runtime/runs/${runRecord.runId}.json`,
      apply,
      createDiscovered,
      discoveredDraftPath,
      escalationDraftPaths,
    };
  } catch (error) {
    await writeReconciliationStatus(
      {
        runId: runRecord.runId,
        reconciliationStatus: "failed",
        reconciledAt: new Date().toISOString(),
      },
      cwd,
    );

    if (error instanceof ReconcileError) {
      await appendAgentAuditEvent(
        {
          command: "reconcile",
          status: "error",
          runId: runRecord.runId,
          taskId: runRecord.taskId,
          message: error.message,
        },
        cwd,
      ).catch(() => undefined);
      throw error;
    }

    const message = error instanceof Error ? error.message : String(error);
    await appendAgentAuditEvent(
      {
        command: "reconcile",
        status: "error",
        runId: runRecord.runId,
        taskId: runRecord.taskId,
        message,
      },
      cwd,
    ).catch(() => undefined);
    throw new ReconcileError(
      "PAA011",
      `Reconciliation failed for run ${runRecord.runId}: ${message}`,
    );
  }
}
