/**
 * Architecture Spec Template
 *
 * USAGE TIMING: Use when documenting a significant architectural component or system.
 *
 * Typical frequency: 2-8 times per project
 *
 * DO NOT use for:
 * - Individual features or small components
 * - When existing architecture documentation is sufficient
 * - During routine task implementation
 */
export function defaultArchitectureSpecTemplate(): string {
  return [
    "# Architecture Spec Template",
    "",
    "Use this template to document a significant architectural component or system.",
    "",
    "## Name",
    "",
    "<architecture-component-name>",
    "",
    "## Purpose",
    "",
    "Describe why this architectural component exists and what problem it solves.",
    "",
    "...",
    "",
    "## Scope",
    "",
    "Define the boundaries of what this architecture spec covers.",
    "",
    "### In Scope",
    "",
    "- ...",
    "",
    "### Out of Scope",
    "",
    "- ...",
    "",
    "## Definitions",
    "",
    "Define key terms, concepts, and entities used in this architecture.",
    "",
    "- **Term A**: ...",
    "- **Term B**: ...",
    "",
    "## Design",
    "",
    "### Architecture Overview",
    "",
    "High-level description of the architecture design.",
    "",
    "...",
    "",
    "### Components",
    "",
    "List and describe the major components:",
    "",
    "- **Component A**: ...",
    "- **Component B**: ...",
    "",
    "### Interactions",
    "",
    "Describe how components interact:",
    "",
    "...",
    "",
    "### Technology Stack",
    "",
    "List relevant technologies, frameworks, and tools:",
    "",
    "- ...",
    "",
    "## Data Model",
    "",
    "### Entities",
    "",
    "Key data entities and their relationships:",
    "",
    "- **Entity A**: ...",
    "- **Entity B**: ...",
    "",
    "### State Management",
    "",
    "How state is managed in this architecture:",
    "",
    "...",
    "",
    "### Data Flow",
    "",
    "Describe how data moves through the system:",
    "",
    "...",
    "",
    "## Owning Domain",
    "",
    "Which domain from `arch-domains/` owns this architecture:",
    "",
    "- ...",
    "",
    "## MVP Constraints",
    "",
    "### Required for MVP",
    "",
    "Features and capabilities required for minimum viable architecture:",
    "",
    "- [ ] ...",
    "- [ ] ...",
    "",
    "### Technical Constraints",
    "",
    "Technical limitations or requirements for MVP:",
    "",
    "- ...",
    "",
    "### Acceptance Criteria",
    "",
    "How to verify MVP architecture is complete:",
    "",
    "- ...",
    "",
    "## Phase 2+ Enhancements",
    "",
    "### Future Capabilities",
    "",
    "Features planned for post-MVP phases:",
    "",
    "- ...",
    "",
    "### Scalability Considerations",
    "",
    "How this architecture can scale:",
    "",
    "- ...",
    "",
    "### Technical Debt",
    "",
    "Known shortcuts taken for MVP that should be addressed:",
    "",
    "- ...",
    "",
    "## Implementation Notes",
    "",
    "### Related Tasks",
    "",
    "- ...",
    "",
    "### Related Decisions",
    "",
    "- ...",
    "",
    "### Code Targets",
    "",
    "Specific files or modules where this architecture is implemented:",
    "",
    "- ...",
    "",
  ].join("\n");
}
