/**
 * Milestone Gap Closure Report Template
 *
 * USAGE TIMING: This template should ONLY be used when ALL tasks in a milestone have reached "done" status.
 *
 * DO NOT use this template:
 * - During task creation
 * - When any task is still in-progress or blocked
 * - For individual task completion
 * - During mid-milestone reviews
 *
 * Trigger conditions for creating a Gap Closure Report:
 * 1. All tasks in planned/ have status: "done"
 * 2. All tasks in discovered/ have status: "done"
 * 3. Milestone objectives are met or formally deferred
 * 4. Team is ready to transition to next milestone
 *
 * Typical frequency: Once per milestone at completion
 */
export function defaultMilestoneGapClosureReportTemplate(): string {
  return [
    "# Milestone Gap Closure Report",
    "",
    "Use this template to document milestone completion status, coverage gaps, and improvement recommendations.",
    "",
    "## Report Metadata",
    "",
    "- **Milestone ID**: ...",
    "- **Phase ID**: ...",
    "- **Report Date**: ...",
    "- **Report Author**: ...",
    "",
    "---",
    "",
    "## Executive Summary",
    "",
    "### Milestone Status",
    "",
    "- **Overall Status**: [ ] Complete | [ ] Incomplete | [ ] Blocked",
    "- **Completion Percentage**: ...%",
    "- **Key Outcomes Achieved**: ...",
    "- **Critical Blockers**: ...",
    "",
    "### High-Level Assessment",
    "",
    "Brief summary of milestone success, key learnings, and next steps.",
    "",
    "...",
    "",
    "---",
    "",
    "## Coverage Audit",
    "",
    "### Planned Tasks",
    "",
    "| Task ID | Title | Status | Completion % |",
    "|---------|-------|--------|--------------|",
    "| 001     | ...   | done   | 100%         |",
    "| 002     | ...   | done   | 100%         |",
    "",
    "### Discovered Tasks",
    "",
    "| Task ID | Title | Status | Why Discovered |",
    "|---------|-------|--------|----------------|",
    "| ...     | ...   | ...    | ...            |",
    "",
    "### Decisions Made",
    "",
    "| Decision ID | Title | Status | Impact |",
    "|-------------|-------|--------|--------|",
    "| ...         | ...   | ...    | ...    |",
    "",
    "### Architecture Artifacts",
    "",
    "- [ ] Architecture documentation updated",
    "- [ ] Domain specifications created/updated",
    "- [ ] Module topology updated",
    "- [ ] Standards documented",
    "",
    "### Test Coverage",
    "",
    "- **Unit Tests**: ...% coverage",
    "- **Integration Tests**: ...% coverage",
    "- **E2E Tests**: ...",
    "",
    "### Documentation Coverage",
    "",
    "- [ ] User-facing documentation complete",
    "- [ ] Developer documentation complete",
    "- [ ] API documentation complete",
    "- [ ] Architecture diagrams updated",
    "",
    "---",
    "",
    "## Remaining Gaps",
    "",
    "### Incomplete Tasks",
    "",
    "| Task ID | Title | % Complete | Blockers | Next Steps |",
    "|---------|-------|------------|----------|------------|",
    "| ...     | ...   | ...%       | ...      | ...        |",
    "",
    "### Missing Artifacts",
    "",
    "List artifacts that were expected but not delivered:",
    "",
    "- ...",
    "",
    "### Deferred Work",
    "",
    "List intentionally deferred work with justification:",
    "",
    "- **Item**: ...",
    "  - **Reason**: ...",
    "  - **Planned for**: ...",
    "",
    "### Known Issues",
    "",
    "List known bugs, technical debt, or quality issues:",
    "",
    "- **Issue**: ...",
    "  - **Severity**: High | Medium | Low",
    "  - **Resolution Plan**: ...",
    "",
    "### Risk Assessment",
    "",
    "Identify risks that emerged during milestone execution:",
    "",
    "- **Risk**: ...",
    "  - **Impact**: ...",
    "  - **Mitigation**: ...",
    "",
    "---",
    "",
    "## Template Improvements",
    "",
    "### What Worked Well",
    "",
    "Identify templates, processes, and practices that were effective:",
    "",
    "- ...",
    "",
    "### What Didn't Work",
    "",
    "Identify templates, processes, and practices that need improvement:",
    "",
    "- ...",
    "",
    "### Recommended Template Changes",
    "",
    "Specific recommendations for template or process improvements:",
    "",
    "1. **Change**: ...",
    "   - **Rationale**: ...",
    "   - **Applies to**: Task template | Decision template | Documentation template | Other",
    "",
    "### Process Improvements",
    "",
    "Recommendations for workflow or process changes:",
    "",
    "- ...",
    "",
    "### Tool Enhancements",
    "",
    "Recommendations for CLI or tooling improvements:",
    "",
    "- ...",
    "",
    "---",
    "",
    "## Lessons Learned",
    "",
    "### Technical Lessons",
    "",
    "- ...",
    "",
    "### Process Lessons",
    "",
    "- ...",
    "",
    "### Communication Lessons",
    "",
    "- ...",
    "",
    "---",
    "",
    "## Next Milestone Recommendations",
    "",
    "### Preparation Checklist",
    "",
    "- [ ] Review and incorporate template improvements",
    "- [ ] Address critical gaps from this milestone",
    "- [ ] Update architecture artifacts",
    "- [ ] Brief team on lessons learned",
    "",
    "### Planning Considerations",
    "",
    "- ...",
    "",
    "---",
    "",
    "## Appendix",
    "",
    "### Metrics",
    "",
    "- **Total Tasks**: ...",
    "- **Tasks Completed**: ...",
    "- **Average Task Duration**: ...",
    "- **Decisions Made**: ...",
    "- **Lines of Code Added**: ...",
    "- **Lines of Code Modified**: ...",
    "- **Test Coverage Change**: ...%",
    "",
    "### Links",
    "",
    "- Milestone Overview: ...",
    "- Phase Overview: ...",
    "- Related Decisions: ...",
    "",
  ].join("\n");
}
